version: "3.8"

services:
  backend:
    container_name: backend-efinanceira
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017
      - DB_NAME=efinanceira
    networks:
      - rede-backend      
      
  mongo:
    container_name: mongo
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - rede-backend

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_AUTHDATABASE=admin
  #   depends_on:
  #     - mongo
  #   networks:
  #     - rede-backend   

volumes:
  mongo-data:

networks:
  rede-backend:
    driver: bridge